ALTER TABLE alert ADD COLUMN lat REAL CHECK(lat BETWEEN -90 AND 90);
ALTER TABLE alert ADD COLUMN lon REAL CHECK(lon BETWEEN -180 AND 180);
ALTER TABLE alert ADD COLUMN radius_m INTEGER CHECK(radius_m BETWEEN 100 AND 100000);
