from __future__ import annotations

import argparse
import difflib
import re
import sys
import tomllib
from collections import Counter
from pathlib import Path
from typing import Any

STATE_ORDER = (
    "designed",
    "implemented",
    "automated_tested",
    "simulated",
    "single_node_field_tested",
    "two_node_field_tested",
    "hardware_gated",
    "production_ready",
)
EVIDENCE_KINDS = {"automated", "acceptance", "field", "hardware", "operations"}
README_START = "<!-- capability-summary:start -->"
README_END = "<!-- capability-summary:end -->"
_ID = re.compile(r"^[a-z][a-z0-9_]*$")
_COMMIT = re.compile(r"^(?:HEAD|[0-9a-f]{7,40})$")
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


class ManifestError(ValueError):
    pass


def load_manifest(path: Path, root: Path) -> dict[str, Any]:
    value = tomllib.loads(path.read_text(encoding="utf-8"))
    validate_manifest(value, root)
    return value


def validate_manifest(value: dict[str, Any], root: Path) -> None:
    if value.get("schema_version") != 1:
        raise ManifestError("schema_version must be 1")
    if not _DATE.fullmatch(str(value.get("as_of", ""))):
        raise ManifestError("as_of must be an ISO date")
    states = value.get("states")
    if not isinstance(states, dict) or tuple(states) != STATE_ORDER:
        raise ManifestError(f"states must be defined in this order: {', '.join(STATE_ORDER)}")
    for state, definition in states.items():
        if not isinstance(definition, dict) or not _text(definition.get("label")):
            raise ManifestError(f"state {state} requires a label")
        if not _text(definition.get("definition")):
            raise ManifestError(f"state {state} requires a definition")

    capabilities = value.get("capabilities")
    if not isinstance(capabilities, list) or not capabilities:
        raise ManifestError("capabilities must be a non-empty list")
    seen: set[str] = set()
    for capability in capabilities:
        if not isinstance(capability, dict):
            raise ManifestError("each capability must be a table")
        identifier = str(capability.get("id", ""))
        if not _ID.fullmatch(identifier) or identifier in seen:
            raise ManifestError(f"invalid or duplicate capability id: {identifier}")
        seen.add(identifier)
        for key in ("area", "present", "maturity"):
            if not _text(capability.get(key)):
                raise ManifestError(f"{identifier}.{key} is required")
        maturity = str(capability["maturity"])
        if maturity not in states:
            raise ManifestError(f"{identifier}.maturity is unknown: {maturity}")
        introduced = str(capability.get("introduced_commit", ""))
        if not re.fullmatch(r"[0-9a-f]{7,40}", introduced):
            raise ManifestError(f"{identifier}.introduced_commit must be a Git commit")
        verification = capability.get("verification")
        if not isinstance(verification, dict):
            raise ManifestError(f"{identifier}.verification is required")
        if not _text(verification.get("release")):
            raise ManifestError(f"{identifier}.verification.release is required")
        if not _COMMIT.fullmatch(str(verification.get("commit", ""))):
            raise ManifestError(f"{identifier}.verification.commit must be HEAD or a Git commit")
        if not _DATE.fullmatch(str(verification.get("date", ""))):
            raise ManifestError(f"{identifier}.verification.date must be an ISO date")
        evidence = capability.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            raise ManifestError(f"{identifier} requires at least one evidence item")
        for item in evidence:
            if not isinstance(item, dict) or item.get("kind") not in EVIDENCE_KINDS:
                raise ManifestError(f"{identifier} has an invalid evidence kind")
            relative = Path(str(item.get("path", "")))
            if relative.is_absolute() or ".." in relative.parts or not relative.parts:
                raise ManifestError(f"{identifier} has an unsafe evidence path: {relative}")
            if not (root / relative).is_file():
                raise ManifestError(f"{identifier} evidence does not exist: {relative}")
            if not _text(item.get("description")):
                raise ManifestError(f"{identifier} evidence requires a description")
        for key in ("limitations", "roadmap"):
            entries = capability.get(key)
            if not isinstance(entries, list) or not all(_text(item) for item in entries):
                raise ManifestError(f"{identifier}.{key} must be a list of non-empty strings")


def render_features(value: dict[str, Any]) -> str:
    states: dict[str, dict[str, str]] = value["states"]
    capabilities: list[dict[str, Any]] = value["capabilities"]
    lines = [
        "<!-- Generated by tools/check_capabilities.py from docs/capabilities.toml. -->",
        "<!-- Edit the TOML source, then run: python tools/check_capabilities.py -->",
        "",
        "# Features and maturity",
        "",
        "Outpost is pre-release. Maturity records the strongest relevant evidence category; it is",
        "not a claim that every lower category is complete. `Production-ready` requires an",
        "explicit release decision and is never inferred from test count alone.",
        "",
        f"Evidence snapshot: **{value['as_of']}**. Verification commit `HEAD` means the exact",
        "revision on which CI runs this manifest check.",
        "",
        "## Maturity states",
        "",
        "| State | Definition |",
        "| --- | --- |",
    ]
    for state in STATE_ORDER:
        lines.append(f"| {states[state]['label']} | {_cell(states[state]['definition'])} |")
    lines.extend(
        [
            "",
            "## Capability matrix",
            "",
            "| Capability | Present behavior | Maturity | Verification |",
            "| --- | --- | --- | --- |",
        ]
    )
    for capability in capabilities:
        verification = capability["verification"]
        verified = (
            f"{verification['release']} @ `{verification['commit']}` "
            f"({verification['date']}); introduced `{capability['introduced_commit']}`"
        )
        lines.append(
            f"| {_cell(capability['area'])} | {_cell(capability['present'])} | "
            f"{states[capability['maturity']]['label']} | {verified} |"
        )
    lines.extend(["", "## Evidence and limitations", ""])
    for capability in capabilities:
        lines.extend(
            [
                f"### {capability['area']}",
                "",
                f"Maturity: **{states[capability['maturity']]['label']}**.",
                "",
                "Evidence:",
                "",
            ]
        )
        for item in capability["evidence"]:
            label = str(item["kind"]).replace("_", " ").title()
            lines.append(
                f"- {label}: [{item['path']}]({_doc_link(str(item['path']))}) — "
                f"{item['description']}"
            )
        lines.extend(["", "Known limitations:", ""])
        if capability["limitations"]:
            lines.extend(f"- {item}" for item in capability["limitations"])
        else:
            lines.append(
                "- No capability-specific limitation recorded beyond the global boundaries."
            )
        if capability["roadmap"]:
            lines.extend(["", "Related roadmap:", ""])
            lines.extend(f"- {_roadmap_link(item)}" for item in capability["roadmap"])
        lines.append("")
    lines.extend(
        [
            "## Global boundaries",
            "",
            "- No 1.0 compatibility promise exists yet.",
            "- Automated or simulated evidence does not replace radio-range, power-loss, thermal,",
            "  security, or disaster exercises on the deployment hardware.",
            "- Environmental feeds are informational and retain source timestamps.",
            "- Emergency keyword matching remains off by default because both false positives and",
            "  missed detections are safety risks.",
            "",
        ]
    )
    return "\n".join(lines)


def render_readme_summary(value: dict[str, Any]) -> str:
    states: dict[str, dict[str, str]] = value["states"]
    capabilities: list[dict[str, Any]] = value["capabilities"]
    counts = Counter(str(item["maturity"]) for item in capabilities)
    count_text = ", ".join(
        f"{states[state]['label']} {counts[state]}" for state in STATE_ORDER if counts[state]
    )
    production = counts["production_ready"]
    readiness = (
        f"{production} capability is marked production-ready."
        if production == 1
        else (
            f"{production} capabilities are marked production-ready."
            if production
            else "No capability is marked production-ready."
        )
    )
    return "\n".join(
        [
            README_START,
            f"Capability evidence snapshot ({value['as_of']}): {len(capabilities)} tracked — "
            f"{count_text}. {readiness} See [Features and maturity]"
            "(docs/FEATURES.md) for test, field,",
            "hardware, revision, limitation, and roadmap evidence.",
            README_END,
        ]
    )


def update_readme(content: str, summary: str) -> str:
    if content.count(README_START) != 1 or content.count(README_END) != 1:
        raise ManifestError("README must contain exactly one capability summary marker pair")
    before, remainder = content.split(README_START, 1)
    _, after = remainder.split(README_END, 1)
    return f"{before}{summary}{after}"


def run(source: Path, features: Path, readme: Path, root: Path, *, check: bool) -> int:
    value = load_manifest(source, root)
    expected_features = render_features(value)
    original_readme = readme.read_text(encoding="utf-8")
    expected_readme = update_readme(original_readme, render_readme_summary(value))
    if not check:
        features.write_text(expected_features, encoding="utf-8")
        readme.write_text(expected_readme, encoding="utf-8")
        print(f"wrote {features} and refreshed {readme}")
        return 0
    failures = 0
    failures += _check_file(features, expected_features)
    if expected_readme != original_readme:
        failures += 1
        print(f"generated capability summary is stale: {readme}", file=sys.stderr)
    if not failures:
        print(f"capability evidence is current: {len(value['capabilities'])} capabilities")
    return 1 if failures else 0


def _check_file(path: Path, expected: str) -> int:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return 0
    print(f"generated capability document is stale: {path}", file=sys.stderr)
    for line in difflib.unified_diff(
        actual.splitlines(), expected.splitlines(), fromfile=str(path), tofile="generated"
    ):
        print(line, file=sys.stderr)
    return 1


def _text(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _cell(value: object) -> str:
    return " ".join(str(value).split()).replace("|", "\\|")


def _doc_link(path: str) -> str:
    return path.removeprefix("docs/") if path.startswith("docs/") else f"../{path}"


def _roadmap_link(value: str) -> str:
    if re.fullmatch(r"#[0-9]+", value):
        number = value[1:]
        return f"[Issue {value}](https://github.com/baal-bot/Outpost-Meshtastic/issues/{number})"
    return value


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or verify capability maturity evidence")
    parser.add_argument("--check", action="store_true", help="fail when generated docs are stale")
    parser.add_argument("--source", type=Path, default=Path("docs/capabilities.toml"))
    parser.add_argument("--features", type=Path, default=Path("docs/FEATURES.md"))
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    arguments = parser.parse_args()
    root = Path.cwd()
    try:
        return run(
            arguments.source,
            arguments.features,
            arguments.readme,
            root,
            check=arguments.check,
        )
    except (ManifestError, OSError, tomllib.TOMLDecodeError) as exc:
        print(f"capability evidence error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
