#!/usr/bin/env python3
"""Generate the mesh command catalogue from production CommandSpec declarations."""

from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path

from outpost.app import OutpostApp
from outpost.config import Config
from outpost.router.models import ChannelUse, CommandSpec

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DOCUMENT = ROOT / "docs" / "COMMANDS.md"
START = "<!-- command-catalogue:start -->"
END = "<!-- command-catalogue:end -->"
CHANNEL_LABELS = {
    ChannelUse.GENERAL: "General",
    ChannelUse.BBS_READ: "BBS read",
    ChannelUse.BBS_WRITE: "BBS write",
    ChannelUse.REPORT: "Incident report",
    ChannelUse.ALERT: "Alert",
    ChannelUse.AI: "Local AI",
}


def registered_specs() -> list[CommandSpec]:
    """Read every shipped command from the actual application registry."""
    with tempfile.TemporaryDirectory(prefix="outpost-command-catalogue-") as temporary:
        root = Path(temporary)
        config = Config.model_validate(
            {
                "store": {
                    "path": str(root / "outpost.db"),
                    "tiles_path": str(root / "tiles"),
                    "releases_path": str(root / "releases"),
                }
            }
        )
        app = OutpostApp(config)
        return app.router.registry.known_commands()


def _cell(value: object) -> str:
    return str(value).replace("|", r"\|").replace("\n", " ").strip()


def _help(value: str) -> str:
    syntax, separator, purpose = value.partition("·")
    rendered = f"`{_cell(syntax)}`"
    return f"{rendered} · {_cell(purpose)}" if separator else rendered


def render_catalogue(specs: list[CommandSpec]) -> str:
    lines = [
        START,
        "<!-- Generated by tools/check_commands.py from production CommandSpec declarations. -->",
        "<!-- Edit CommandSpec metadata, then run: python tools/check_commands.py -->",
        "",
        "| Command and aliases | Syntax and purpose | Minimum trust | "
        "Channel capability | Airtime | State |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for spec in specs:
        aliases = ""
        if spec.aliases:
            aliases = "<br>Aliases: " + ", ".join(f"`{_cell(alias)}`" for alias in spec.aliases)
        lines.append(
            f"| `{_cell(spec.name)}`{aliases} | {_help(spec.help_short)} | "
            f"{spec.min_trust.name.title()} | {CHANNEL_LABELS[spec.channel_use]} | "
            f"{spec.airtime_class.value} | {'Changes state' if spec.mutates else 'Read-only'} |"
        )
    lines.extend([END, ""])
    return "\n".join(lines)


def update_document(document: str, catalogue: str) -> str:
    if document.count(START) != 1 or document.count(END) != 1:
        raise ValueError("COMMANDS.md must contain exactly one command catalogue marker pair")
    before, remainder = document.split(START, 1)
    _, after = remainder.split(END, 1)
    return f"{before}{catalogue.rstrip()}{after}"


def run(document_path: Path, *, check: bool) -> int:
    try:
        current = document_path.read_text(encoding="utf-8")
        specs = registered_specs()
        expected = update_document(current, render_catalogue(specs))
    except (OSError, ValueError) as error:
        print(f"Command catalogue error: {error}", file=sys.stderr)
        return 1
    if check:
        if current != expected:
            print(
                "Command catalogue is stale; run: python tools/check_commands.py",
                file=sys.stderr,
            )
            return 1
        print(f"Command catalogue is current ({len(specs)} commands).")
        return 0
    document_path.write_text(expected, encoding="utf-8")
    print(f"Updated {document_path} from {len(specs)} commands.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--document", type=Path, default=DEFAULT_DOCUMENT)
    args = parser.parse_args()
    return run(args.document, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
